version: "3.0"

## example command（with docker command）

## build
# docker build -t {image name} .
## Build a specific stage
# docker build -t {image name} --target {stage name} .

## run
# docker run --rm -it {image name}
# docker run --rm -it hazuki3417/build-cpp-lambda-table-image-analysis

## example command（with docker-compose command）

## build
# docker-compose build {target name}
# docker-compose build --no-cache build-lib
# docker-compose build --no-cache build-function
# docker-compose build --no-cache build-image

## run
# docker-compose run --rm {target name}
# docker-compose run --rm build-lib
# docker-compose run --rm build-function
# docker-compose run --rm build-image

## selected build target
# docker build -t hazuki3417/build-container-lambda-table-image-analysis --target {stage name} .
# docker build -t hazuki3417/build-container-lambda-table-image-analysis --target build-cpp .
# docker build -t hazuki3417/build-container-lambda-table-image-analysis --target build-container .


services:
  
  build-lib:
    build:
      context: ./submodules
      dockerfile: Dockerfile.build-lib
    image: hazuki3417/build-lib:latest
    container_name: build-lib
    volumes:
      - type: bind
        source: "./"
        target: "/tmp/workspace"

  build-function:
    image: hazuki3417/build-lib:latest
    volumes:
      - type: bind
        source: "./"
        target: "/tmp"
        
  build-image:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hazuki3417/build-image:latest
    container_name: build-image
