FROM hazuki3417/cpp-build-leptonica:latest
ENV DEBIAN_FRONTEND=noninteractive

ARG workspace=/var/workspace

WORKDIR ${workspace}

# build & install opencv
RUN git clone https://github.com/opencv/opencv.git && \
    cd opencv && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON .. && \
    make -j8 && \
    make install
