FROM hazuki3417/cpp-build-boost:latest
ENV DEBIAN_FRONTEND=noninteractive

ARG workspace=/var/workspace

WORKDIR ${workspace}

# build & install googletest
RUN git clone https://github.com/google/googletest.git && \
    cd googletest && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install
