FROM hazuki3417/cpp-build-base:latest
ENV DEBIAN_FRONTEND=noninteractive

ARG workspace=/var/workspace

WORKDIR ${workspace}

# build & install aws lambda cpp runtime
RUN git clone https://github.com/awslabs/aws-lambda-cpp-runtime.git && \
    cd aws-lambda-cpp-runtime && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make && make install
