FROM hazuki3417/cpp-build-googletest:latest
ENV DEBIAN_FRONTEND=noninteractive

ARG workspace=/var/workspace

WORKDIR ${workspace}

# build & install leptonica
RUN git clone https://github.com/DanBloomberg/leptonica.git && \
    cd leptonica && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_PROG=1 && \
    make && \
    make install
